version: "3.8"

services:
  ocserv:
    container_name: ocserv
    image: morganonbass/ocserv-ldap:latest
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    environment:
      LISTEN_PORT: 443
      TUNNEL_MODE: 'all'
      TUNNEL_ROUTES: '10.221.166.0/24'
      DNS_SERVERS: 10.221.166.5
      SPLIT_DNS_DOMAINS: 'twink.lan'
      CLIENTNET: 10.221.166.0
      CLIENTNETMASK: 255.255.255.0
      BASEDN: 'dc=twink,dc=lan'
      LDAPURI: 'ldap://10.221.166.5/'
      BINDDN: 'CN=lumen,CN=Users,DC=twink,DC=lan'
      BINDPW: 'Asdf1234'
      SEARCHSCOPE: 'sub'
      PAM_LOGIN_ATTRIBUTE: 'sAMAccountName'
      CA_CN: 'VPN CA'
      CA_ORG: 'OCSERV'
      CA_DAYS: 9999
      SRV_CN: 'vpn.flashazs.ru'
      SRV_ORG: 'flashazs'
      SRV_DAYS: 9999
    volumes:
      - './config/:/config/'
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: unless-stopped